name: Run Python Code

on:
  push:
    branches:
      - main

jobs:
  run-python-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Python Code
      run: |
        python main.py
